name: Periodic Update
on:
  schedule:
    # Run twice per day (at 1:00UTC, 13:00UTC)
    - cron: "0 1,13 * * *"
  workflow_dispatch:
jobs:
  periodic-auto-update:
    runs-on: ubuntu-latest
    environment: token-refresh
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - run: pip install -r requirements.txt

      - name: Run script that collects tokens
        env:
          ONEINCH_API_KEY: ${{ secrets.ONEINCH_API_KEY }}
        run: |
          python3 aggregate_tokens.py && python3 generate_readme.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
  
      - name: Commit changes
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_user_name: obvious-bot
          commit_user_email: ansuman@obvious.technology
          commit_message: Token Updates

      - uses: shallwefootball/s3-upload-action@master
        if: success()
        name: Upload List to S3
        with:
          aws_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: ${{ vars.S3_SOURCE_DIR }}
          destination_dir: ${{ vars.S3_OUTPUT_DIR }}
