name: Upload changes to S3
on:
  workflow_dispatch:
jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    environment: token-refresh
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
  
      - name: Upload List to S3
        if: success()
        run: |
          aws s3 sync ${{ vars.S3_SOURCE_DIR }} s3://${{ secrets.AWS_BUCKET }}/${{ vars.S3_OUTPUT_DIR }} --include "*.json" --dryrun
